<?php
/** @var Invade\OpenWeather\Block\Weather $block */
$weather = $block->getWeather();
?>
<div id="weather-data" class="weather-data">
    <?php foreach ($weather as $item): ?>
    <h1>Weather in <?= $item->getCity() ?> city at <?= $item->getCreatedAt(); ?></h1>
        <p>Country: <span id="country"><?= $item->getCountry() ?></span></p>
        <p>Description: <span id="desc"><?= $item->getDescription() ?></span></p>
        <p>Temperature(f): <span id="temperature"><?= $item->getTemperature() ?></span></p>
        <p>Feels like(f): <span id="feels_like"><?= $item->getFeelsLike() ?></span></p>
        <p>Pressure(hPa): <span id="pressure"><?= $item->getPressure() ?></span></p>
        <p>Humidity(%): <span id="humidity"><?= $item->getHumidity() ?></span></p>
        <p>Wind speed(m/s): <span id="wind_speed"><?= $item->getWindSpeed() ?></span></p>
        <p>Sunrise: <span id="sunrise"><?= $item->getSunrise() ?></span></p>
        <p>Sunset: <span id="sunset"><?= $item->getSunset() ?></span></p>
        <p>Latitude: <span id="latitude"><?= $item->getLat() ?></span></p>
        <p>Longitude: <span id="longitude"><?= $item->getLon() ?></span></p>
    <?php endforeach; ?>
</div>
